In [3]:
import pandas as pd

In [4]:
domino = pd.read_csv("../Data/dominoMaejang.csv")
domino.head()

   지점명                          매장주소
0   개포  서울특별시 강남구 논현로 58 (개포동, 동진빌딩)
1   논현            서울특별시 강남구 학동로4길 15
2   대치        서울특별시 강남구 대치동  역삼로 444
3   삼성      서울특별시 강남구 봉은사로 451 (삼성동)
4  압구정      서울특별시 강남구 압구정로 306 (신사동)

In [5]:
domino_daegu = domino.iloc[374:,:]
domino_daegu.reset_index(drop=True, inplace=True)

In [6]:
domino_daegu['매장주소'] = domino_daegu['매장주소'].str.replace('부산광역시', '부산')
domino_daegu['매장주소'] = domino_daegu['매장주소'].str.replace('제주도', '제주특별자치도')

/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_63227/229696629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domino_daegu['매장주소'] = domino_daegu['매장주소'].str.replace('부산광역시', '부산')
/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_63227/229696629.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domino_daegu['매장주소'] = domino_daegu['매장주소'].str.replace('제주도', '제주특별자치도')

In [7]:

domino_daegu.iloc[99,:] = '제주특별자치도 제주시 승천로 70 (1층)'

/Users/tj/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/Users/tj/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [8]:
domino_daegu.tail(20)

                         지점명                                    매장주소
85                        괴정                    부산 사하구 사하로 169 (괴정동)
86                       다대포                    부산 사하구 다대로 571 (다대동)
87                        하단                  부산 사하구 하신중앙로 333 (하단동)
88                        대신            부산 서구 구덕로 303-1, 1층 (서대신동2가)
89                        수영              부산 수영구 수영로 640-1, 1층 (광안동)
90                        연산                   부산 연제구 중앙대로 1173 (1층)
91                      연제토곡                      부산 연제구 과정로 156, 1층
92                        영도                  부산 영도구 태종로 329-1 (청학동)
93                      반여재송             부산 해운대구 반여로 23 (반여동, 도미노피자)
94                      부산반송             부산 해운대구 아랫반송로21번길 106 (반송동)
95                        센텀                   부산 해운대구 해운대로 535 (우동)
96                       해운대       부산 해운대구 해운대로 793 부산자생한방병원 상가 108호
97                     제주서귀포                   제주특별자치도 서귀포시 신서귀로 118
98                      제주노형                제주특별자치도 제주시 연북로 18 (노형동)
99   제주특별자치도 제주시 승천로 70 (1층)                 제주특별자치도 제주시 승천로 70 (1층)
100                     제주화북               제주특별자치도 제주시 화삼로 19 (화북1동)
101                     세종다정      세종특별자치시 한누리대로 331 SR파크센텀 103호,104호
102                     세종보람     세종특별자치시 시청대로 209 금강르네상스 1층 107,108호
103                     세종아름  세종특별자치시 보듬3로 91, 115~116호 (아름동, 해피라움4)
104                      조치원                 세종특별자치시 조치원읍 문화길 39  1층

In [9]:
domino_daegu['구'] = [region.split()[0] for region in domino_daegu['매장주소']]
domino_daegu.head()

/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_63227/3298595988.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domino_daegu['구'] = [region.split()[0] for region in domino_daegu['매장주소']]

    지점명                        매장주소      구
0  대구효목            대구광역시 동구 동부로 204  대구광역시
1    봉덕       대구광역시 남구 봉덕로 66 (봉덕동)  대구광역시
2  대구성서       대구광역시 달서구 이곡공원로1길 108  대구광역시
3  대구용산  대구광역시 달서구 달구벌대로 1565 (죽전동)  대구광역시
4    상인            대구광역시 달서구 월배로 52  대구광역시

In [10]:
domino_daegu.head()

    지점명                        매장주소      구
0  대구효목            대구광역시 동구 동부로 204  대구광역시
1    봉덕       대구광역시 남구 봉덕로 66 (봉덕동)  대구광역시
2  대구성서       대구광역시 달서구 이곡공원로1길 108  대구광역시
3  대구용산  대구광역시 달서구 달구벌대로 1565 (죽전동)  대구광역시
4    상인            대구광역시 달서구 월배로 52  대구광역시

In [11]:
domino_daegu['구'].unique()

array(['대구광역시', '전라남도', '전라북도', '광주광역시', '울산광역시', '부산', '제주특별자치도',
       '세종특별자치시'], dtype=object)

In [12]:
import json
import folium

In [13]:
# geo_path = "../Data/skorea_municipalities_geo_simple.json"
# geo_str = json.load(open(geo_path, encoding='utf-8'))

# map = folium.Map(
#     location=[37.5502, 126.982],
#     zoom_start=10.5,
#     tiles='Stamen Toner',

# )
# folium.Choropleth(
#     geo_data=geo_str,
#     data=domino_daegu,
#     columns=[domino_daegu.index, '가격'],
#     fill_color='PuRd',
#     key_on='feature.id'
# ).add_to(map)

KeyError: '가격'

In [14]:
import urllib.request

client_id = "knyo4tcwfn"
client_secret = "GpwWAGlloYMUQhozeVUbtzSqKjxV5bgDmK1gYWMv"

# 위도, 경도
lng_daegu = []
lat_daegu = []
ext = []
# 기름 비싼 매장 10
for address in domino_daegu['매장주소']:
    encText = urllib.parse.quote(address)
    url = "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query=" + encText #JSON 형식
    request = urllib.request.Request(url)
    request.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    request.add_header("X-NCP-APIGW-API-KEY",client_secret)

    response = urllib.request.urlopen(request)
    rescode = response.getcode()

    # 200이면 정상
    if rescode == 200:
        response_body = response.read()
        enText = response_body.decode('utf-8')
    else:
        print("Error Code:" + rescode)

    import json
    data1 = json.loads(enText)


    lng_daegu.append(data1['addresses'][0]['x'])
    lat_daegu.append(data1['addresses'][0]['y'])

In [ ]:
# # top10
# for name, lat, lng in zip(oil_price_top10['Oil_store'], lat_top, lng_top):
#     folium.Marker(
#         [lat,lng], popup=name,
#         icon=folium.Icon(icon='flag',color='red')
#         ).add_to(map)
#     folium.CircleMarker(
#         [lat, lng],
#         radius=10,
#         fill_color='skyblue',
#         fill_opacity=0.7,
#         popup=name,
        
#     ).add_to(map)

In [15]:
len(lng_daegu)

105

In [16]:
len(lat_daegu)

105

In [17]:
domino_daegu['lng'] = lng_daegu
domino_daegu['lat'] = lat_daegu

/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_63227/2778832390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domino_daegu['lng'] = lng_daegu
/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_63227/2778832390.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  domino_daegu['lat'] = lat_daegu

In [18]:
domino_daegu.head(10)

,지점명,매장주소,구,lng,lat
0,대구효목,대구광역시 동구 동부로 204,대구광역시,128.6344143,35.8783957
1,봉덕,대구광역시 남구 봉덕로 66 (봉덕동),대구광역시,128.5976587,35.8446452
2,대구성서,대구광역시 달서구 이곡공원로1길 108,대구광역시,128.5087380,35.8556928
3,대구용산,대구광역시 달서구 달구벌대로 1565 (죽전동),대구광역시,128.5378344,35.8508863
4,상인,대구광역시 달서구 월배로 52,대구광역시,128.5203359,35.8131736
5,월성,대구광역시 달서구 조암로 85-1,대구광역시,128.5210867,35.8226646
6,대구다사,대구광역시 달성군 다사읍 왕선로 54 (매곡리),대구광역시,128.4645052,35.8642431
7,대구현풍,"대구광역시 달성군 현풍면 테크노대로 24, 1층 108,109호(테크노플라자1)",대구광역시,128.4495370,35.6887636
8,대구화원,대구광역시 달성군 화원읍 명천로 255,대구광역시,128.4912243,35.7978355
9,대구이시아폴리스,"대구광역시 동구 팔공로 241 1층 111호, 112호(봉무동)",대구광역시,128.6402718,35.9205000

In [19]:
domino_daegu.to_csv("../Data/domino_daegu.csv", index=False)