# 리디북스 일반도서 베스트셀러
https://ridibooks.com/bestsellers/general?order=monthly&page=1

In [1]:

from bs4 import BeautifulSoup

import urllib.request as req

url = "https://ridibooks.com/bestsellers/general?order=monthly&page=1"
res = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser")

soup.select("#page_best > div.book_macro_wrapper.js_book_macro_wrapper > div.book_macro_110.book_macro_portrait.book_macro_column_6.recommended_book > div.book_metadata_wrapper > h3 > a > span")

[<span class="title_text js_highlight_helper hidden">
                         원씽
             </span>]

> copy selector로 가져오니 클래스 이름이 보임

In [2]:
# selector를 간단하게 사용하기

from bs4 import BeautifulSoup

import urllib.request as req

url = "https://ridibooks.com/bestsellers/general?order=monthly&page=1"
res = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser")

scraping_lists = soup.select(".title_text")
print(scraping_lists)

[<span class="title_text js_highlight_helper hidden">
                        원씽
            </span>, <span class="title_text js_highlight_helper hidden">
                        역행자
            </span>, <span class="title_text js_highlight_helper hidden">
                        작별인사
            </span>, <span class="title_text js_highlight_helper hidden">
                        인플레이션에서 살아남기
            </span>, <span class="title_text js_highlight_helper hidden">
                        변화하는 세계 질서
            </span>, <span class="title_text js_highlight_helper hidden">
                        피스타운
            </span>, <span class="title_text js_highlight_helper hidden">
                        악마의 계약서는 만기 되지 않는다
            </span>, <span class="title_text js_highlight_helper hidden">
                        불편한 편의점
            </span>, <span class="title_text js_highlight_helper hidden">
                        내가 틀릴 수도 있습니다
            </span>, <span class="title_text js_highlight_helper hidden">
                        최재천의 공부
            </span>, <span class="title_text js_highlight_helper hidden">
                                  개정판 | 하얀 늑대들
                    </span>, <span class="title_text js_highlight_helper hidden">
                        잠시 동안 빛은 이곳에
            </span>, <span class="title_text js_highlight_helper hidden">
                        심해어
            </span>, <span class="title_text js_highlight_helper hidden">
                        사이후이, 싸이파이
            </span>, <span class="title_text js_highlight_helper hidden">
                        친밀한 이방인
            </span>, <span class="title_text js_highlight_helper hidden">
                        도파민네이션
            </span>, <span class="title_text js_highlight_helper hidden">
                        구글 엔지니어는 이렇게 일한다
            </span>, <span class="title_text js_highlight_helper hidden">
                        멘탈을 바꿔야 인생이 바뀐다
            </span>, <span class="title_text js_highlight_helper hidden">
                        플라스틱 세대
            </span>, <span class="title_text js_highlight_helper hidden">
                        덫
            </span>, <span class="title_text js_highlight_helper hidden">
                        나의 투자는 새벽 4시에 시작된다
            </span>, <span class="title_text js_highlight_helper hidden">
                        레스토랑 안의 낯선 자들
            </span>, <span class="title_text js_highlight_helper hidden">
                        물고기는 존재하지 않는다
            </span>, <span class="title_text js_highlight_helper hidden">
                        원씽
            </span>, <span class="title_text js_highlight_helper hidden">
                        버드나무
            </span>, <span class="title_text js_highlight_helper hidden">
                        브라질에 비가 내리면 스타벅스 주식을 사라
            </span>, <span class="title_text js_highlight_helper hidden">
                        모든 것은 기본에서 시작한다
            </span>, <span class="title_text js_highlight_helper hidden">
                        밝은 밤
            </span>, <span class="title_text js_highlight_helper hidden">
                        부자 아빠 가난한 아빠 20주년 특별 기념판
            </span>, <span class="title_text js_highlight_helper hidden">
                        나를 단단하게 만드는 심리학
            </span>, <span class="title_text js_highlight_helper hidden">
                        프로젝트 헤일메리
            </span>]

In [3]:
# 책 권수 확인

len(scraping_lists)

31

> 별표 붙은 책 때문에 31권을 가져왔음

In [4]:
scraping_lists = scraping_lists[1:]
len(scraping_lists)

30

In [5]:
book_lists = []
for book_list in scraping_lists:
    book_lists.append(book_list.string)

len(book_lists)

30

In [6]:
book_lists

['          \n                        역행자\n            ',
 '          \n                        작별인사\n            ',
 '          \n                        인플레이션에서 살아남기\n            ',
 '          \n                        변화하는 세계 질서\n            ',
 '          \n                        피스타운\n            ',
 '          \n                        악마의 계약서는 만기 되지 않는다\n            ',
 '          \n                        불편한 편의점\n            ',
 '          \n                        내가 틀릴 수도 있습니다\n            ',
 '          \n                        최재천의 공부\n            ',
 '          \n                                  개정판 | 하얀 늑대들\n                    ',
 '          \n                        잠시 동안 빛은 이곳에\n            ',
 '          \n                        심해어\n            ',
 '          \n                        사이후이, 싸이파이\n            ',
 '          \n                        친밀한 이방인\n            ',
 '          \n                        도파민네이션\n            ',
 '          \n                        구글 엔지니어는 이렇게 일한다\n            ',
 '          \n                        멘탈을 바꿔야 인생이 바뀐다\n            ',
 '          \n                        플라스틱 세대\n            ',
 '          \n                        덫\n            ',
 '          \n                        나의 투자는 새벽 4시에 시작된다\n            ',
 '          \n                        레스토랑 안의 낯선 자들\n            ',
 '          \n                        물고기는 존재하지 않는다\n            ',
 '          \n                        원씽\n            ',
 '          \n                        버드나무\n            ',
 '          \n                        브라질에 비가 내리면 스타벅스 주식을 사라\n            ',
 '          \n                        모든 것은 기본에서 시작한다\n            ',
 '          \n                        밝은 밤\n            ',
 '          \n                        부자 아빠 가난한 아빠 20주년 특별 기념판\n            ',
 '          \n                        나를 단단하게 만드는 심리학\n            ',
 '          \n                        프로젝트 헤일메리\n            ']

In [7]:
book_lists = []
for book_list in scraping_lists:
    book_lists.append(book_list.string.strip())

book_lists

['역행자',
 '작별인사',
 '인플레이션에서 살아남기',
 '변화하는 세계 질서',
 '피스타운',
 '악마의 계약서는 만기 되지 않는다',
 '불편한 편의점',
 '내가 틀릴 수도 있습니다',
 '최재천의 공부',
 '개정판 | 하얀 늑대들',
 '잠시 동안 빛은 이곳에',
 '심해어',
 '사이후이, 싸이파이',
 '친밀한 이방인',
 '도파민네이션',
 '구글 엔지니어는 이렇게 일한다',
 '멘탈을 바꿔야 인생이 바뀐다',
 '플라스틱 세대',
 '덫',
 '나의 투자는 새벽 4시에 시작된다',
 '레스토랑 안의 낯선 자들',
 '물고기는 존재하지 않는다',
 '원씽',
 '버드나무',
 '브라질에 비가 내리면 스타벅스 주식을 사라',
 '모든 것은 기본에서 시작한다',
 '밝은 밤',
 '부자 아빠 가난한 아빠 20주년 특별 기념판',
 '나를 단단하게 만드는 심리학',
 '프로젝트 헤일메리']

# DataFrame 만들기
---

In [8]:
# Rank List 만들기
rank = list(range(1,31))

In [9]:
data = []

for i,j in zip(rank, book_lists):
    data.append([i,j])

In [10]:
data[:5]

[[1, '역행자'], [2, '작별인사'], [3, '인플레이션에서 살아남기'], [4, '변화하는 세계 질서'], [5, '피스타운']]

In [11]:
import pandas as pd

page1 = pd.DataFrame(data=data, columns=[['Rank','bookTitle']])
page1.head()

  Rank     bookTitle
0    1           역행자
1    2          작별인사
2    3  인플레이션에서 살아남기
3    4    변화하는 세계 질서
4    5          피스타운

In [12]:
# csv로 저장
page1.to_csv("../Data/ridi_page1.csv", index=False)
pd.read_csv("../Data/ridi_page1.csv").head

<bound method NDFrame.head of     Rank                 bookTitle
0      1                       역행자
1      2                      작별인사
2      3              인플레이션에서 살아남기
3      4                변화하는 세계 질서
4      5                      피스타운
5      6        악마의 계약서는 만기 되지 않는다
6      7                   불편한 편의점
7      8             내가 틀릴 수도 있습니다
8      9                   최재천의 공부
9     10              개정판 | 하얀 늑대들
10    11              잠시 동안 빛은 이곳에
11    12                       심해어
12    13                사이후이, 싸이파이
13    14                   친밀한 이방인
14    15                    도파민네이션
15    16          구글 엔지니어는 이렇게 일한다
16    17           멘탈을 바꿔야 인생이 바뀐다
17    18                   플라스틱 세대
18    19                         덫
19    20        나의 투자는 새벽 4시에 시작된다
20    21             레스토랑 안의 낯선 자들
21    22             물고기는 존재하지 않는다
22    23                        원씽
23    24                      버드나무
24    25   브라질에 비가 내리면 스타벅스 주식을 사라
25    26           모든 것은 기본에서 시작한다
26    27                      밝은 밤
27    28  부자 아빠 가난한 아빠 20주년 특별 기념판
28    29           나를 단단하게 만드는 심리학
29    30                 프로젝트 헤일메리>

---
### 1page의 도서명과 hyperlink를 통한 작품 소개 내용 가져오기

In [3]:
# Hyper Link 정보 가져오기

from bs4 import BeautifulSoup

import urllib.request as req

url = "https://ridibooks.com/bestsellers/general?order=monthly&page=1"
res = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser")

In [18]:

hyperlinks = soup.select(".title_link")

In [19]:
hyperlink = []

for i in hyperlinks:
    hyperlink.append("https://ridibooks.com" + i['href'])

print(hyperlink)

['https://ridibooks.com/books/1468000044?_rdt_sid=bestseller_star&_rdt_idx=0', 'https://ridibooks.com/books/606002388?_rdt_sid=bestseller&_rdt_idx=0', 'https://ridibooks.com/books/4271000014?_rdt_sid=bestseller&_rdt_idx=1', 'https://ridibooks.com/books/4139000033?_rdt_sid=bestseller&_rdt_idx=2', 'https://ridibooks.com/books/1890000285?_rdt_sid=bestseller&_rdt_idx=3', 'https://ridibooks.com/books/4575000003?_rdt_sid=bestseller&_rdt_idx=4', 'https://ridibooks.com/books/1648000475?_rdt_sid=bestseller&_rdt_idx=5', 'https://ridibooks.com/books/2177000101?_rdt_sid=bestseller&_rdt_idx=6', 'https://ridibooks.com/books/4803001974?_rdt_sid=bestseller&_rdt_idx=7', 'https://ridibooks.com/books/1546000953?_rdt_sid=bestseller&_rdt_idx=8', 'https://ridibooks.com/books/1176000018?_rdt_sid=bestseller&_rdt_idx=9', 'https://ridibooks.com/books/4578000004?_rdt_sid=bestseller&_rdt_idx=10', 'https://ridibooks.com/books/4912000001?_rdt_sid=bestseller&_rdt_idx=11', 'https://ridibooks.com/books/4926000001?_rdt_sid=bestseller&_rdt_idx=12', 'https://ridibooks.com/books/371001540?_rdt_sid=bestseller&_rdt_idx=13', 'https://ridibooks.com/books/745000210?_rdt_sid=bestseller&_rdt_idx=14', 'https://ridibooks.com/books/443001038?_rdt_sid=bestseller&_rdt_idx=15', 'https://ridibooks.com/books/4239000039?_rdt_sid=bestseller&_rdt_idx=16', 'https://ridibooks.com/books/4647000003?_rdt_sid=bestseller&_rdt_idx=17', 'https://ridibooks.com/books/4909000001?_rdt_sid=bestseller&_rdt_idx=18', 'https://ridibooks.com/books/606002383?_rdt_sid=bestseller&_rdt_idx=19', 'https://ridibooks.com/books/4927000001?_rdt_sid=bestseller&_rdt_idx=20', 'https://ridibooks.com/books/1508006000?_rdt_sid=bestseller&_rdt_idx=21', 'https://ridibooks.com/books/1468000044?_rdt_sid=bestseller&_rdt_idx=22', 'https://ridibooks.com/books/4910000001?_rdt_sid=bestseller&_rdt_idx=23', 'https://ridibooks.com/books/2596000037?_rdt_sid=bestseller&_rdt_idx=24', 'https://ridibooks.com/books/2337000035?_rdt_sid=bestseller&_rdt_idx=25', 'https://ridibooks.com/books/371002440?_rdt_sid=bestseller&_rdt_idx=26', 'https://ridibooks.com/books/682000717?_rdt_sid=bestseller&_rdt_idx=27', 'https://ridibooks.com/books/4698000005?_rdt_sid=bestseller&_rdt_idx=28', 'https://ridibooks.com/books/510001099?_rdt_sid=bestseller&_rdt_idx=29']

In [70]:
# 1번 책으로 hyper link test

url = hyperlink[0]
res = req.urlopen(url)
soup = BeautifulSoup(res, "html.parser")
book_contents = soup.select_one(".folded")
print(book_contents.text)

<원씽> 인생의 반전을 불러오는 단순함의 힘
당신의 삶을 소모시키는 멀티태스킹의 허상에서 벗어나라!

아마존 종합 베스트셀러 1위!
《월스트리트 저널》 종합 베스트셀러 1위!
《뉴욕 타임스》《USA 투데이》《워싱턴 포스트》 베스트셀러!
전 세계 독자들이 주목한 2013년 최고의 책!

당신에게는 성공의 첫 번째 도미노가 있는가?
주위를 돌아보면 ‘무슨 일을 해도 어쩌면 저렇게 잘 풀릴까’라는 생각이 들게 하는 사람이 한 명씩은 꼭 있기 마련이다. 반대로 정말 열심히 살지만 제대로 풀리는 게 없다고 여기는 사람들도 있다. 이들은 타고난 팔자라거나 운이 좋았다는 식으로 다른 사람의 성공을 단정 짓고 자신들의 ‘운 없음’에 좌절하곤 한다. 하지만 그건 사실이 아니다. 위대한 성과를 내는 남다른 인생과 평범한 인생을 결정짓는 차이는 바로 ‘꼭 해야 할 일’에만 파고들었느냐, ‘필요 없는 일’에 에너지를 낭비했느냐에 있다.
성공은 도미노처럼 작동한다. 성공한 사람들은 늘 성공에 ‘꼭 필요한 일들’의 ‘순서’를 계획해놓고 ‘가장 알맞은 타이밍’에 첫 번째 일을 ‘제대로’ 해낸다. 한 번 넘어지기 시작하면 멈추지 않는 도미노처럼 그들은 처음의 성공을 다음 행동과 연결 지음으로써 더 크고 더 위대한 성공을 이끌어낸다. 그들은 첫 번째 도미노만 정확히 찾아 쓰러뜨린다면 줄지어 늘어선 수많은 도미노는 자연히 쓰러지게 된다는 성공의 도미노 효과를 누구보다 잘 알고 있다. 모든 일을 시작하게 하는 단 하나의 도미노, 우리가 ‘원씽(The One Thing)’이라 부르는 이것을 찾아낼 수만 있다면 누구나 술술 잘 풀리는 인생을 경험할 수 있다.

The One Thing, 복잡한 세상에서 나만의 중심을 잃지 않는 법
《원씽 The One Thing》은 미국에서 가장 큰 투자개발 회사의 대표이자 총 130만 부 이상이 팔린 베스트셀러의 저자 게리 켈러와 제이 파파산이 쓴, 이제까지의 통념을 뒤엎는 신개념 자기계발서이다. 이 책이 말하고 있는 인생의 성공과 행복에 대한 단순한 진리는 바로 ‘원씽’(The One Thing), 자신에게 가장 중요한 단 하나, 가장 중요한 한 가지 일에 집중하고 파고들라는 것이다.
‘원씽One Thing’은 세상의 모든 분야에 적용될 수 있는 개념이다. 기업의 입장에서는 회사를 상징하거나 정체성을 드러내는 하나의 제품이나 서비스, 개인의 삶에서는 자신의 인생을 의미 있게 만들어주는 한 가지 목표를 의미한다. 다시 말해 기업의 수익성과 매출, 개인의 직업과 연봉과 같은 단선적인 시각이 아닌 보다 본질을 관통하는 주제이며 목적을 항해 나아가도록 해주는 원천인 것이다. 그래서 저자는 이 책에서 “당신에게 가장 중요한 ‘단 하나’는 무엇인가?”(What‘s your ONE Thing?)라고 계속해서 질문을 던진다.

중요하지 않은 것은 버려라.
당신의 에너지를 오직 한 가지에 집중하라!
자신만의 ‘원씽’을 찾는 방법을 알려주기 위해 씌여진 이 책은 총 3부로 구성되어 있다. 먼저 1부에서는 모두가 성공의 원칙이라고 믿어온 여섯 가지 주장(모든 일이 다 중요하다/멀티태스킹은 곧 능력이다/성공은 철저한 자기관리에서 온다/의지만 있다면 못할 일은 없다/균형 잡힌 삶이 아름답다/크게 벌이는 일은 위험하다)의 허상을 조목조목 비판한다. 이런 잘못된 믿음으로 인해 우리는 바쁘게 일하는 것만이 능사이고, 모든 일을 다 완벽히 잘하기 위해 동시에 여러 가지 일을 하다 결국 아무것도 제대로 하지 못하고 지쳐 떨어지고 만다는 것이다. 또한 이렇게 여러 일을 해내지 못하면 ‘자기관리’와 ‘의지’가 부족한 것으로 자책하게 만드는 것 또한 각종 미디어와 자기계발서가 만들어낸 거짓일 뿐이라고 저자는 지적한다. 우리에게 필요한 것은 중요한 일을 지속시킬 수 있는 ‘습관’일 뿐이며 이러한 습관 만들기에 필요한 실질적인 지침을 소개한다.
2~3부에서는 성공을 둘러싼 허상에서 벗어나 자신만의 큰 목표를 세우도록 우리를 안내한다. 그 첫 단계에 해당하는 ‘초점탐색 질문’은 ‘아무리 강렬한 햇빛이라도 초점을 맞추기 전에는 절대로 종이 한 장 태울 수 없다’는 말처럼 최종의 목표인 ‘원씽’에 다가가기 위해 지금 당장 해야 하는 ‘원씽’이 무엇인지 알려준다. 그리고 더 큰 성공에 도달하기 위한 도미노를 세우는 데 필요한 요소들을 분석한다. 이 과정을 통해 성공의 열쇠는 우리가 ‘모든 일’을 다 잘 해낼 때 오는 것이 아니라 가장 핵심적인 일을 가장 ‘적합한’ 순간에 해내는 것임을 깨닫게 해주고 그 핵심적인 일을 찾기 위한 우선순위를 결정하는 법에 대해 명확히 설명해준다.

인생에도 뺄셈이 필요하다
오늘날 대부분의 사람들은 자신의 인생에 중요하지 않은 일들을 하고 필요 없는 관계들을 유지하느라 인생의 대부분의 시간과 에너지를 빼앗기고 있다. 당장 오늘 하루를 돌아보자. 오늘 한 일 중에서 자신이 생각하는 인생의 최종 목표에 반걸음이라도 가까이 가게 해준 것이 있는지, 혹 나의 꿈이 아닌 누군가의 꿈을 이뤄주기 위해 나의 소중한 하루를 희생하지 않았는지 말이다. 당신의 인생에서 가장 중요한 ‘원씽One Thing’은 무엇인가? 자신이 지금 하고 있는 일이 인생의 ‘원씽One Thing’에 이르기 위한 도미노 블록 중 하나인가? 이 두 가지 질문에 자신 있게 대답하지 못한다면 지금 바로 저자들의 이야기에 귀를 기울여야 할 것이다. 결코 모든 일을 다 잘하려고 하지 마라. 한꺼번에 많은 일을 해내는 사람이 승자가 되는 것이 아니라 한 가지라도 제대로 해내는 사람이 최종 승자가 된다는 단순명쾌한 진리를 한번 따라가 보자. 그리고 사방에 흩어져 있는 도미노들의 열을 우선순위에 맞춰 세우고 첫 번째 도미노를 쓰러뜨리자. 뒤로 줄줄이 넘어질 준비가 되어 있는 더 큰 성공으로 이어지는 긴 도미노를 발견하게 될 것이다.

추천의 글

과중한 업무와 멀티태스킹이 만연한 이 세상에서 단순하지만 명확한 메시지를 전달하는 이 책은 베스트셀러에 오를 수밖에 없다. 당신이 에너지를 한 가지에 몰입하라. 놀라운 삶이 시작될 것이다.
_《뉴욕 타임스》

이 책은 당신의 성공을 가로막고, 당신의 계획을 좌절시키는 거짓말들이 무엇인지 보여 준다. 그리고 ‘단 하나’(The One Thing)를 통해 완벽하게 새로운 전략을 제안한다. 당신이 일하는 방식, 선택하는 방식, 그리고 성과를 내는 방식 그 모든 부분에서 이 책은 획기적인 변화를 선사할 것이다.
_《월스트리트 저널》

이 책은 어떻게 멀티태스킹을 가장한 ‘주의력 결핍’에서 벗어나며, 우선순위를 정하고 한 곳에 집중해야 하는지 알려 준다. 세계에서 가장 큰 투자개발 회사를 소유한 백만장자가 들려주는 가치 있는 성공의 조언들이 가득하다.
_《포브스》

쳇바퀴 안에서 늘 똑같은 인생이 계속된다고 느끼는가? 지금 당장 이 책을 집어라. 당신의 삶에 기막힌 변화를 가져다줄 것이다. 당신의 선택에 인생의 성공이 달려 있다.
_NBC

In [71]:
# Test후 적용
bookContents = []

for url in hyperlink:
    res = req.urlopen(url)
    soup = BeautifulSoup(res, "html.parser")
    book_contents = soup.select_one(".folded")
    bookContents.append(book_contents.text)

In [75]:
import pandas as pd

ridibooks = pd.read_csv("../Data/ridi_page1.csv")

In [76]:
ridibooks['Contents'] = pd.Series(bookContents)
ridibooks.head()

   Rank     bookTitle                                           Contents
0     1           역행자  <원씽> 인생의 반전을 불러오는 단순함의 힘\r\n당신의 삶을 소모시키는 멀티태스킹...
1     2          작별인사  <역행자> 오타쿠 흙수저에서 월 1억 자동수익을 실현한 무자본 연쇄창업마,\r\n라...
2     3  인플레이션에서 살아남기  <작별인사> 누구도 도와줄 수 없는 상황, 혼자 헤쳐나가야 한다\r\n지켜야 할 약...
3     4    변화하는 세계 질서  <인플레이션에서 살아남기> \n\n40년 만에 찾아온 인플레의 역습, \r\n당신의...
4     5          피스타운  <변화하는 세계 질서> \n\n《원칙 Principles: Life & Work》으...

In [80]:
from bs4 import BeautifulSoup

import urllib.request as req

title_text_list = []

for i in range(1,8):

    url = "https://ridibooks.com/bestsellers/general?order=monthly&page=%d"%i
    res = req.urlopen(url)
    soup = BeautifulSoup(res, "html.parser")

    title_text = soup.select(".title_text")
    hyperlink_list = soup.select(".title_link")

    for i in title_text:
        title_text_list.append(i.string.strip())

원씽
역행자
작별인사
인플레이션에서 살아남기
변화하는 세계 질서
피스타운
악마의 계약서는 만기 되지 않는다
불편한 편의점
내가 틀릴 수도 있습니다
최재천의 공부
개정판 | 하얀 늑대들
잠시 동안 빛은 이곳에
심해어
사이후이, 싸이파이
친밀한 이방인
도파민네이션
구글 엔지니어는 이렇게 일한다
멘탈을 바꿔야 인생이 바뀐다
플라스틱 세대
덫
나의 투자는 새벽 4시에 시작된다
레스토랑 안의 낯선 자들
물고기는 존재하지 않는다
원씽
버드나무
브라질에 비가 내리면 스타벅스 주식을 사라
모든 것은 기본에서 시작한다
밝은 밤
부자 아빠 가난한 아빠 20주년 특별 기념판
나를 단단하게 만드는 심리학
프로젝트 헤일메리
2022 제13회 젊은작가상 수상작품집
특별한 아이, 특별한 엄마
삼국지 원전 완역판 세트(10권)
돈, 뜨겁게 사랑하고 차갑게 다루어라
아노말리
데일 카네기 자기관리론
당신만 모르는 일의 법칙 51
부의 추월차선(10주년 기념 에디션)
운명을 바꾸는 부동산 투자 수업 (기초편)
개정판 | 살인자의 기억법
사피엔스
파이어
부자의 그릇
메롱해치, 궁녀를 부탁해!
달러구트 꿈 백화점 2
룬의 아이들 - 윈터러 완전판
저주토끼
면접을 위한 CS 전공지식 노트
칼
여덟 건의 완벽한 살인
그리움의 끝
위쳐 본편 전권 세트
이어령의 마지막 수업
시맨틱 에러 대본집
홍학의 자리
레슨 인 케미스트리 1
돈의 속성
개정 번역판 | 해리 포터와 마법사의 돌
럭키 드로우
지구 끝의 온실
인생명강 07 - 더 찬스
코스모스
데일 카네기 인간관계론
마음의 법칙
세븐
책들의 부엌
2022년 국제 현충일 특별 집회
아티스트 웨이, 마음의 소리를 듣는 시간
웰씽킹
보도 섀퍼의 이기는 습관
샤일록의 아이들
노이즈
H마트에서 울다
칵테일, 러브, 좀비
오은영의 화해
우리가 빛의 속도로 갈 수 없다면
행성 1
마지막 몰입 : 나를 넘어서는 힘
아몬드
평생 현금이 마르지 않는 투자법
어서 오세요, 휴남동 서점입니다
나는 대출 없이 0원으로 소형 아파트를 산다
거꾸로 읽는 세계사
빌 게이츠 넥스트 팬데믹을 대비하는 법
사랑의 기술(5판)
어린이라는 세계
성공하는 사람들의 7가지 습관
언제나 밤인 세계
클루지
기브앤테이크
케이크를 자르지 못하는 아이들
맛있어서 지속 가능한 디디미니 다이어트 레시피
장면들
무례한 사람에게 휘둘리지 않는 법
문재인의 위로
애쓰지 않아도
10배의 법칙 : 성공과 실패를 가르는 유일한 차이
마스터스 오브 스케일
타이탄의 도구들
사는 게 고통일 때, 쇼펜하우어
거의 모든 행동 표현의 영어
부의 시나리오
개정판｜나는 까칠하게 살기로 했다
젊은 ADHD의 슬픔
구의 증명
박찬욱의 몽타주
미움받을 용기
팀 켈러의 탈기독교시대 전도
운명을 바꾸는 부동산 투자 수업 (실전편)
히든 스토리
마음이 흐르는 대로
인간 실격
어떻게 말해줘야 할까
아주 작은 습관의 힘
백년 목
공정하다는 착각
빅이슈코리아 The Big Issue No.277
감정 어휘
개정판｜나는 둔감하게 살기로 했다
소식주의자
여행의 이유
생각에 관한 생각
소년이 온다 : 한강 장편소설
하늘을 나는 타이어
오십의 주역공부
당신은 결국 무엇이든 해내는 사람
무엇이 옳은가
더 시스템 THE SYSTEM
노르웨이의 숲
문예춘추사 셜록 홈즈 전집 세트
긴긴밤
묵상과 설교 - 2014년 1월호
좋아하는 곳에 살고 있나요?
백만장자 시크릿
망원동 브라더스
도메인 주도 개발 시작하기
개정판｜헤드 퍼스트 디자인 패턴
2022 제5회 한국과학문학상 수상작품집
뇌, 욕망의 비밀을 풀다
걷기의 세계
묘사의 힘
프로세스 이코노미
하트 오브 비즈니스
인스타 브레인
소크라테스 익스프레스
제 마음대로 살아보겠습니다
눈 감으면 보이는 것들
차녀 힙합
프로그래머의 뇌
올바르게 승리하라
리더의 질문법
[세트] 조지 오웰 컬렉션: 1984, 동물농장(전 2권)
삶이 던지는 질문은 언제나 같다
완전한 행복
돈의 심리학
그릿: 100쇄 기념 리커버 에디션
동급생
저만치 혼자서
부자의 독서법
왼손잡이 우주
나답게 일한다는 것
지리의 힘
일러스트로 배우는 채색 테크닉 -7가지 테마 컬러의 활용-
아들아, 부동산 공부 해야 한다
보이지 않는 중국
시맨틱 에러 포토에세이
아비투스
레버리지
정의란 무엇인가
미드나잇 라이브러리
멘탈의 연금술
엘리어트 파동이론
개정판 | 론리하트
연금술사
직업으로서의 소설가
퇴마록 국내편
눈물을 마시는 새 세트
현명한 반도체 투자
어떻게 물리학을 사랑하지 않을 수 있을까?
천 개의 파랑
개정판 | 빅터 프랭클의 죽음의 수용소에서
트라우마 사전
지적 대화를 위한 넓고 얕은 지식 1
데일 카네기 인간관계론
50 이후, 건강을 결정하는 7가지 습관
시선으로부터,
시크릿
위기주도학습법
프로그래머가 알아야 할 알고리즘 40
개정판｜부의 인문학
나는 왜 네 말이 힘들까
개정판 | 피프티 피플
넛지: 파이널 에디션
기이현상청 사건일지
아킬레우스의 노래
데미안
합리적 남자
개정판 | 현명한 투자자 1
나의 월급 독립 프로젝트
하이 아웃풋 매니지먼트