In [1]:
# 랜덤 포레스트
import pandas as pd

In [2]:
# 붓꽃의 데이터 읽어 들이기
csv = pd.read_csv("../Data/iris.csv")

In [3]:
csv.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
# 필요한 열 추출하기
csv_data = csv[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
csv_label = csv['Name']

In [5]:
# 학습 전용 데이터와 테스트 전용 데이터로 나누기

from sklearn.model_selection import train_test_split

train_data, test_data, train_label, test_label = train_test_split(
    csv_data,
    csv_label,
)

In [6]:
# 데이터 학습 시키고 예측하기
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
clf = RandomForestClassifier()

clf.fit(train_data, train_label)

RandomForestClassifier()

In [7]:
# 정확도
clf.score(test_data, test_label)

0.9210526315789473

In [14]:
# Confusion Matrix *********

metrics.accuracy_score(test_label, clf.predict(test_data))
# metrics.classification_report(clf.predict(test_data, test_label))

TypeError: predict() takes 2 positional arguments but 3 were given

-----
# 독버섯과 관련된 데이터를 사용한 머신러닝

In [ ]:
# 데이터 획득하기

import pandas as pd
import urllib.request as req

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

In [ ]:
# 데이터 읽기
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

# Data 정제하기

In [ ]:
 # 연습하기
 print(ord('a'))
 print(chr(97))

97
a

In [ ]:
# 데이터 내부의 문자를 숫자로 변환하기
label = []
data = []

for row_index, row in mr.iterrows():
    # print(row_index, row)
    # print(row.loc[1:])
    label.append(row.loc[0])
    row_data = []
    for v in row.loc[1:]:
        row_data.append(ord(v))
    data.append(row_data)

print(data[0:20])

[[120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 121, 116, 97, 102, 99, 98, 107, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103], [98, 115, 119, 116, 108, 102, 99, 98, 110, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 109], [120, 121, 119, 116, 112, 102, 99, 110, 110, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 103, 102, 110, 102, 119, 98, 107, 116, 101, 115, 115, 119, 119, 112, 119, 111, 101, 110, 97, 103], [120, 121, 121, 116, 97, 102, 99, 98, 110, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 107, 110, 103], [98, 115, 119, 116, 97, 102, 99, 98, 103, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 107, 110, 109], [98, 121, 119, 116, 108, 102, 99, 98, 110, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 115, 109], [120, 121, 119, 116, 112, 102, 99, 110, 112, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 118, 103], [98, 115, 121, 116, 97, 102, 99, 98, 103, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 109], [120, 121, 121, 116, 108, 102, 99, 98, 103, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103], [120, 121, 121, 116, 97, 102, 99, 98, 110, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 109], [98, 115, 121, 116, 97, 102, 99, 98, 119, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 115, 103], [120, 121, 119, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 110, 118, 117], [120, 102, 110, 102, 110, 102, 119, 98, 110, 116, 101, 115, 102, 119, 119, 112, 119, 111, 101, 107, 97, 103], [115, 102, 103, 102, 110, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 110, 121, 117], [102, 102, 119, 102, 110, 102, 119, 98, 107, 116, 101, 115, 115, 119, 119, 112, 119, 111, 101, 110, 97, 103], [120, 115, 110, 116, 112, 102, 99, 110, 110, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 103], [120, 121, 119, 116, 112, 102, 99, 110, 110, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 110, 115, 117], [120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 110, 115, 117]]

In [ ]:
# label을 DataFrame으로 만들기
labelTemp = pd.DataFrame(label)
labelTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [ ]:
# data를 DataFrame으로 만들고 Column을 겹치지 않게 하기
dataTemp = pd.DataFrame(data)
dataTemp.rename(columns=lambda x: x+1, inplace=True)
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [ ]:
# 2개의 DataFrame을 합치기
mr2 = pd.concat([labelTemp, dataTemp], axis='columns')
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [ ]:
# RandomForest로 정확도 측정해 보기 

train_data, test_data, train_label, test_label = train_test_split(
    data,
    label,
)

clf.fit(train_data, train_label)
clf.score(test_data, test_label)

1.0

### One Hot Encoding 실시
: 숫자 데이터가 수자로서 의미가 있으면 상관없지만 위의 데이터는 분류를 위한 데이터 이므로 숫자 크기가 의미가 없다.  
  이때 사용하는 것이 One Hot Encoding 이다.

In [ ]:
# 1번열 data의 종류 확인
mr2[1].unique()

array([120,  98, 115, 102, 107,  99])

In [ ]:
# 연습하기


for i in range(1,23):                                       # 컬럼 고정 네임 1_, 2_, ...
    dataTemp = pd.get_dummies(data=dataTemp, columns=[i], prefix=str(i))

In [ ]:
dataTemp

,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,2_121,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,0,0,0,0,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,1,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
8120,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
8121,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
8122,0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8123,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
mr3 = pd.concat([labelTemp, dataTemp], axis='columns')
mr3.head()

,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,e,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,p,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,e,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
# RandomForest로 정확도 측정해 보기 

train_data, test_data, train_label, test_label = train_test_split(
    dataTemp,
    labelTemp,
)

clf.fit(train_data, train_label)
clf.score(test_data, test_label)

/var/folders/51/xmc_l6t13wv1nc5z6qmyg58r0000gn/T/ipykernel_27199/179167138.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(train_data, train_label)

1.0