### 특성(Feature)공학과 규제(Regularization : 정형화, 규제, 일반화)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/fish.csv")
df.head()

   length   height   width
0     8.4     2.11    1.41
1    13.7     3.53    2.00
2    15.0     3.82    2.43
3    16.2     4.59    2.63
4    17.4     4.59    2.94

> 길이, 높이, 두께로 구성된 Data

In [3]:
# Numpy로 변환
fish_full = df.to_numpy()
fish_full[0:6]

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32]])

In [4]:
df = pd.read_csv("../Data/fish_weight.csv")
df.head()

   weight
0     5.9
1    32.0
2    40.0
3    51.5
4    70.0

In [5]:
fish_weight = df.to_numpy()
fish_weight[0:6]

array([[  5.9],
       [ 32. ],
       [ 40. ],
       [ 51.5],
       [ 70. ],
       [100. ]])

In [6]:
# Train과 Test로 분리
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    fish_full, fish_full, random_state=42
)